//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_prenotazioni
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int id { get; set; }
        public int id_room { get; set; }
        public string email_user { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan begin_time { get; set; }
        public System.TimeSpan end_time { get; set; }
        public bool equipment { get; set; }
        public decimal price { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}
